export default {
  'redbrick-extension' : 'REDBRICK EXTENSION',
  'game-flow' : 'Game Flow',
  event : 'EVENT',
  "management-multiple-similar-objects": "Managing Multiple Similar Objects",
  'gui-object' : 'GUI OBJECT',
  tween : 'TWEEN',
  tips : 'TIPS',
  "continuously-tracking-player" : "Create an object that continuously tracks the player",
  "Making-object-face-to-another" : "Making Object Always Face Target",
  "random-position" : "Setting a Random Position",
  "change-avatar-appearance" : "Changing Avatar Appearance",
  "object-rotation" : "Continuously Rotating Object",
  "how-to-use-clone" : "Using Object Cloning",
  "clone-audio" : "Using Audio Cloning",
  "add-text-to-world" : "Adding Text to the World",
  'sample-game' : 'SAMPLE GAME',
};