export default {
  "collect-items": "Collect items",
  "change-avatar-speed": "Avatar speed change ",
  spawn: "Set the Starting Point",
  respawn: "Return to original position when it falls",
  "create-savepoints": "Create Save Point",
  "squid-game": "Making a stepping stone that disappears when you step on it",
  animations: "Creating an object that moves repeatedly",
  "create-timer": "Create Timer, Countdown",
  "create-game-button": "Create a Game Start button",
  "victory-gui": "Return to first screen at the end of the game",
  "create-shooting": "How to create shooting game",
  debug: "How to debug and error?",
  "create-quarter-view-camera" : "Create quarter view camera",
  "how-to-use-portal" : "Switching to another game",
};
