export default {
  "management-multiple-similar-objects": "Managing Multiple Similar Objects",
  "collect-items": "Collect items",
  "change-avatar-speed": "Avatar speed change ",
  tween: 'Using TWEEN',
  spawn: "Set the Starting Point",
  respawn: "Return to original position when it falls",
  "create-savepoints": "Create Save Point",
  "squid-game": "Making a stepping stone that disappears when you step on it",
  animations: "Creating an object that moves repeatedly",
  "create-timer": "Create Timer, Countdown",
  "create-game-button": "Create a Game Start button",
  "victory-gui": "Return to first screen at the end of the game",
  "create-shooting": "How to create shooting game",
  debug: "How to debug and error?",
  "create-quarter-view-camera" : "Create quarter view camera",
  "how-to-use-portal" : "Switching to another game",
  "change-background-during-playing" : "Changing the Background Image During playing",
  "continuously-tracking-player" : "Create an object that continuously tracks the player",
  "create-functionality-pause-game" : "Create function to pause the game",
  "create-functionality-reset-game" : "Create function to reset the game",
  "Making-object-face-to-another" : "Making Object Always Face Target",
  "random-position" : "Setting a Random Position",
  "change-avatar-appearance" : "Changing Avatar Appearance",
  "object-rotation" : "Continuously Rotating Object",
  "how-to-use-clone" : "Using Object Cloning",
};
