export default {
  'redbrick-extension' : '레드브릭 확장',
  'game-flow' : '게임 흐름',
  event : '이벤트',
  "management-multiple-similar-objects" : "다수의 유사한 오브젝트 관리",
  tween: 'TWEEN',
  "create-game-button": "게임 시작 버튼 만들기",
  debug: "디버깅 및 오류 해결 방법은?",
  "create-quarter-view-camera" : "쿼터뷰 카메라 만들기",
  "change-background-during-playing" : "플레이 중 배경이미지 바꾸기",
  "continuously-tracking-player" : "플레이어를 지속적으로 추적하는 오브젝트 만들기",
  "Making-object-face-to-another" : "오브젝트가 항상 특정 객체를 바라보게 만들기",
  "random-position" : "랜덤한 위치 설정하기",
  "change-avatar-appearance" : "아바타 모습 바꾸기",
  "create-progress-bar" : "GUI 프로그래스 바 만들기",
  "create-world-progress-bar" : "WOLRD 프로그래스 바 만들기",
  "object-rotation" : "오브젝트 지속적으로 회전시키기",
  "save-data-to-local-storage" : "로컬 저장소에 데이터 저장하기",
  "how-to-use-clone" : "오브젝트를 복제하여 사용하기",
  "clone-audio" : "오디오를 복제하여 사용하기",
  "add-text-to-world" : "월드에 텍스트 추가하기",
  'sample-game' : '샘플 게임',
};